In [54]:
import numpy as np

In [55]:
# In the below code, various values of x1,x2,...,xn will be tried

# Case 1 : 
x = np.array([0,0,0])
A = np.zeros((len(x)+1,len(x)+1))
for i in range(len(x)):
    A[i][len(x)] = x[i]
    A[len(x)][i] = x[i]
eig_val, eig_vec = np.linalg.eig(A) 
print(eig_val)

[0. 0. 0. 0.]


In [56]:
# Case 2 : 
x = np.array([0,0,1])
A = np.zeros((len(x)+1,len(x)+1))
for i in range(len(x)):
    A[i][len(x)] = x[i]
    A[len(x)][i] = x[i]
eig_val, eig_vec = np.linalg.eig(A) 
print(eig_val)

[ 1. -1.  0.  0.]


In [57]:
# Case 3 : 
x = np.array([0,0,0,1])
A = np.zeros((len(x)+1,len(x)+1))
for i in range(len(x)):
    A[i][len(x)] = x[i]
    A[len(x)][i] = x[i]
eig_val, eig_vec = np.linalg.eig(A) 
print(eig_val)

[ 1. -1.  0.  0.  0.]


In [68]:
# Case 4 : 
x = np.array([3,8,6,2,5])
A = np.zeros((len(x)+1,len(x)+1))
for i in range(len(x)):
    A[i][len(x)] = x[i]
    A[len(x)][i] = x[i]
eig_val, eig_vec = np.linalg.eig(A) 
print(eig_val)

[-1.17473401e+01 -4.44089210e-16  1.17473401e+01  0.00000000e+00
  0.00000000e+00  0.00000000e+00]


#### From the above cases - there are (n-2) zeros as eigenvalue for the given matrix. That is the characteristic polynomial is of the form :
$ \lambda^{n-1}(\lambda^2 + C1\lambda+ C2)$

In [69]:
# Case 5 : 
x = np.array([0,1,0])
A = np.zeros((len(x)+1,len(x)+1))
for i in range(len(x)):
    A[i][len(x)] = x[i]
    A[len(x)][i] = x[i]
eig_val, eig_vec = np.linalg.eig(A) 
print(eig_val)

[ 1. -1.  0.  0.]


In [70]:
# Case 6 : 
x = np.array([1,0,0])
A = np.zeros((len(x)+1,len(x)+1))
for i in range(len(x)):
    A[i][len(x)] = x[i]
    A[len(x)][i] = x[i]
eig_val, eig_vec = np.linalg.eig(A) 
print(eig_val)

[ 1. -1.  0.  0.]


In [71]:
# Case 7 : 
x = np.array([2,0,0])
A = np.zeros((len(x)+1,len(x)+1))
for i in range(len(x)):
    A[i][len(x)] = x[i]
    A[len(x)][i] = x[i]
eig_val, eig_vec = np.linalg.eig(A) 
print(eig_val)

[ 2. -2.  0.  0.]


In [72]:
# Case 8 : 
x = np.array([0,2,0])
A = np.zeros((len(x)+1,len(x)+1))
for i in range(len(x)):
    A[i][len(x)] = x[i]
    A[len(x)][i] = x[i]
eig_val, eig_vec = np.linalg.eig(A) 
print(eig_val)

[ 2. -2.  0.  0.]


In [73]:
# Case 9 : 
x = np.array([0,0,2])
A = np.zeros((len(x)+1,len(x)+1))
for i in range(len(x)):
    A[i][len(x)] = x[i]
    A[len(x)][i] = x[i]
eig_val, eig_vec = np.linalg.eig(A) 
print(eig_val)

[ 2. -2.  0.  0.]


#### From the above cases - the position of the value of $x_i$ doesn't seem to impact the eigen value, hence the coefficients of each power of each xi should be the same

In [74]:
# Case 10 : 
x = np.array([-1,0,0])
A = np.zeros((len(x)+1,len(x)+1))
for i in range(len(x)):
    A[i][len(x)] = x[i]
    A[len(x)][i] = x[i]
eig_val, eig_vec = np.linalg.eig(A) 
print(eig_val)

[ 1. -1.  0.  0.]


In [75]:
# Case 11 : 
x = np.array([3,4,5])
A = np.zeros((len(x)+1,len(x)+1))
for i in range(len(x)):
    A[i][len(x)] = x[i]
    A[len(x)][i] = x[i]
eig_val, eig_vec = np.linalg.eig(A) 
print(eig_val)

[-7.07106781e+00 -3.62557206e-16  7.07106781e+00  0.00000000e+00]


In [76]:
# Case 12 : 
x = np.array([-3,-4,-5])
A = np.zeros((len(x)+1,len(x)+1))
for i in range(len(x)):
    A[i][len(x)] = x[i]
    A[len(x)][i] = x[i]
eig_val, eig_vec = np.linalg.eig(A) 
print(eig_val)

[-7.07106781e+00 -3.62557206e-16  7.07106781e+00  0.00000000e+00]


In [77]:
# Case 13 : 
x = np.array([-3,4,5])
A = np.zeros((len(x)+1,len(x)+1))
for i in range(len(x)):
    A[i][len(x)] = x[i]
    A[len(x)][i] = x[i]
eig_val, eig_vec = np.linalg.eig(A) 
print(eig_val)

[-7.07106781e+00 -3.62557206e-16  7.07106781e+00  0.00000000e+00]


#### From the above cases - the sign of each $x_i$ don't seem to impact the eigen values. Hence $C_1$ and $C_2$ should only contain even powers of x. Also, both the eigen values are of equal magnitude but opposite in sign. Meaning, $-{C_1}^2 =  0 => C_1 = 0$ 


#### Hence the characteristic equation can be written as :
$ \lambda^{n-1}(\lambda^2 + C2)$
